### ISSUE TITLE
Use in a cordova app in android

### ISSUE THREAD

**Issue by jonDel** [patrickmonteiro/quasar-qrcode-reader#3]
I used this example and implemented it in a quasar web app, and it worked fine.
However, when I build it as a cordova android plugin, with the cordova camera plugin installed, even after I set the camera permissions for this app in android, it doesn't seem to work (no camera stream image appears in the app).

**Comment by patrickmonteiro** [comment]
@jonDel That's weird! Because I used it in another project and it worked perfectly.

**Comment by patrickmonteiro** [comment]
@jonDel My advice then is, for cordova use this plugin.

https://github.com/phonegap/phonegap-plugin-barcodescanner

**Comment by jonDel** [comment]
I forgot to comment, when I installed the apk in my Android phone, there was no message asking for grant any permissions for the app. I don't know if this behavior is expected, but for me it seemed wierd.

**Comment by patrickmonteiro** [comment]
@jonDel To request permissions I use another cordova plugin. If you are interested in implementing it, follow an example on my github:
https://github.com/patrickmonteiro/quasar-cordova-permission
